default_platform(:ios)

platform :ios do
  desc "Upload the app to Testflight"
  
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end
  
  lane :testFlight do
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
      )

    match(
      git_url: "git@github.com:enebin/naenio-iOS-match.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
      )

    xcversion(version: "~> 13.0")

    cocoapods(
        clean: true,
        podfile: "./Podfile",
        try_repo_update_on_error: true,
        use_bundle_exec: false
    )

    gym(
      workspace: "Naenio.xcworkspace",
      scheme: "Naenio-deploy",
      configuration: "Release",
      export_options: {
        method: "app-store",
        signingStyle: "manual"
      }
    )	
    
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    
    upload_to_testflight

  end
end
