name: swiftlint

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run swiftlint
        run: swiftlint --config .swiftlint.yml
