name: swiftlint

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
