name: swiftlint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Naenio repository
        uses: actions/checkout@v3 
      
      - name: Fetch base ref
        run: |
          git fetch --prune --no-tags --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/heads/${{ github.base_ref }}

      - name: Run GitHub Action for SwiftLint(Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
