name: swiftlint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      
jobs:
  swiftlint:
    runs-on: macos-latest
    steps:
      - name: Checkout Naenio repository
        uses: actions/checkout@v3 
      
      - name: Run GitHub Action for SwiftLint(Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1

      - name: Run swiftlint
        run: swiftlint --config Naenio-iOS/.swiftlint.yml
