name: Testflight

on:
  push:
    branches: 
      - 'fix/**'

jobs:
  Ready-for-flying:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: 13.4.1


      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          path: Naenio/ignored
          repository: enebin/naenio-ios-ignored
          token: ${{ secrets.ACTION_TOKEN }}
          
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
          
      - run: fastlane testFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}

